[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version = "0.9.0"
version_scheme = "semver"
gpg_sign = true
annotated_tag = true
update_changelog_on_bump = true
major_version_zero = true
version_files = [
  "README.md",
  "oqs/Cargo.toml",
  "oqs-sys/Cargo.toml",
]
