[package]
name = "oqs"
version = "0.7.0"
authors = ["Thom Wiggers <thom@thomwiggers.nl>"]
edition = "2018"
description = "A Rusty interface to Open-Quantum-Safe's liboqs"
readme = "../README.md"
repository = "https://github.com/open-quantum-safe/liboqs-rust"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
libc = "0.2"
cstr_core = { version = "0.2", default-features = false, features = ["alloc"], optional = true }
serde = { version = "1.0", optional = true, default-features = false, features = ["derive", "alloc"] }

[dependencies.oqs-sys]
path = "../oqs-sys"
version = "0.7.0"
default-features = false

[features]
default = ["oqs-sys/openssl", "kems", "sigs"]
no_std = ["cstr_core"]
non_portable = ["oqs-sys/non_portable"]

# algorithms: KEMs
kems = ["oqs-sys/kems"]  # enable kems through oqs-sys
bike = ["oqs-sys/bike"]
classic_mceliece = ["oqs-sys/classic_mceliece"]
frodokem = ["oqs-sys/frodokem"]
hqc = ["oqs-sys/hqc"]
kyber = ["oqs-sys/kyber"]
ntru = ["oqs-sys/ntru"]
ntruprime = ["oqs-sys/ntruprime"]
saber = ["oqs-sys/saber"]
sidh = ["oqs-sys/sidh"]
sike = ["oqs-sys/sike"]
# algorithms: Signature schemes
sigs = ["oqs-sys/sigs"]  # enables all sigs through oqs-sys
dilithium = ["oqs-sys/dilithium"]
falcon = ["oqs-sys/falcon"]
picnic = ["oqs-sys/picnic"]
rainbow = ["oqs-sys/rainbow"]
sphincs = ["oqs-sys/sphincs"]
