[package]
name = "oqs"
version = "0.1.0"
authors = ["Thom Wiggers <thom@thomwiggers.nl>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/thomwiggers/oqs-rs"
license = "MIT or Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1"

[dependencies.oqs-sys]
path = "../oqs-sys"
version = "0.1.0"
default-features = false

[features]
default = ["oqs-sys/openssl"]
