[package]
name = "oqs-sys"
version = "0.1.0"
authors = ["Thom Wiggers <thom@thomwiggers.nl>"]
edition = "2018"
links = "oqs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cmake = "0.1"
bindgen = "0.53"
build-deps = "0.1"

[features]
default = ["openssl"]
openssl = []
docs = []

[package.metadata.docs.rs]
featuress = ["docs"]
